#!/usr/bin/env python3

# Notes:
# - This should work with no arguments.
# - The config file to use is ../config.yaml.
# - This should produce its output and perform operations
#   using the the current working directory

import os
import sys
import argparse
import yaml
from pathlib import Path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
from lib.shellcmd import run_command

debug = True

class CleanVagrant:
    def __init__(self):
        self.config_file = os.path.normpath(os.path.join(os.getcwd(),
                                                         "..",
                                                         "config.yaml"))

    def clean_vagrant(self):
        print("Destroying Vagrant machines from dir: " + os.getcwd())
        cmd = "vagrant destroy -f"
        run_command( cmd )

        # Show status
        cmd = "vagrant status || true"
        run_command( cmd )

def main(argv):
    app = CleanVagrant()
    app.clean_vagrant()

if __name__ == "__main__":
    main(sys.argv[1:])
