#!/usr/bin/env python3

# Notes:
# - This should work with no arguments.
# - The config file to use is ../config.yaml.
# - This should produce its output and perform operations
#   using the the current working directory

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
from lib.shellcmd import run_command

debug = True


class MakefileClean:
    def __init__(self):
        self.config_file = os.path.normpath(os.path.join(os.getcwd(),
                                                         "..",
                                                         "config.yaml"))
        self.script_dir = os.path.dirname(os.path.realpath(__file__))  # Path to this script

    def makefile_clean(self):
        """ Run make clean
        """
        cmd = "make clean"
        run_command(cmd)


def main(argv):
    app = MakefileClean()
    app.makefile_clean()


if __name__ == "__main__":
    main(sys.argv[1:])
