#!/bin/bash

EXTERNAL='google.com'
echo "Ping ${EXTERNAL} from node-1"
ssh node-1 ping -c 1 ${EXTERNAL}

echo "Get IP for node-1"
IP=$(ssh node-1 ip a s | grep eth0 | tail -1 | awk '{print $2}' | cut -d '/' -f 1)
echo "node-1: IP=$IP"

echo "Ping node-1 from node-2"
ssh node-2 ping -c 1 $IP


